spring:
  profiles:
    active: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /management
  endpoint:
    health:
      show-details: always